name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-versions }}-
          php-version: ${{ matrix.php-versions }}

      - name: Check PHP Version
        run: php -v
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Check vendor licenses
        run: composer run-script lic-check
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run static analysis (GrumPHP)
        run: composer run-script grumphp
        with:
          php-version: ${{ matrix.php-versions }}
